# pwn

secureshell:
    build: ./pwn-re/200-secureshell/src
    ports:
        - 7100:7100
    security_opt:
        - seccomp:unconfined

pwnclub:
    build: ./pwn-re/300-pwnclub/src
    ports:
        - 31337:31337
    security_opt:
        - seccomp:unconfined

# web

death_by_1000_curls:
    build: ./web/100-death_by_1000_curls/src
    ports:
        - 43478:43478
    security_opt:
        - seccomp:unconfined

dodona:
    build: ./web/200-Dodona/src
    ports:
        - 4738:4738
    security_opt:
        - seccomp:unconfined

trollsec:
    build: ./web/300-trollsec/src
    ports:
        - 10101:10101
    security_opt:
        - seccomp:unconfined  
