apiVersion: v1
kind: Service
metadata:
  name: web100
spec:
  ports:
   - port: 43478
     targetPort: 43478
  selector:
    app: web100
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web100
spec:
  podSelector:
    matchLabels:
      app: web100
  ingress:
  - ports:
    - port: 43478
    from: []
