apiVersion: v1
kind: Service
metadata:
  name: pwn300
spec:
  ports:
   - port: 31337
     targetPort: 31337
  selector:
    app: pwn300
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: pwn300
spec:
  podSelector:
    matchLabels:
      app: pwn300
  ingress:
  - ports:
    - port: 31337
    from: []
