apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web200
spec:
  replicas: 1
  template:
    metadata:
      name: web200
      labels:
        app: web200
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::503205249670:role/CTFChallengeRole
    spec:
      containers:
        - name: web200
          image: bsidespdx2018/web200
          imagePullPolicy: Always
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
