apiVersion: v1
kind: Service
metadata:
  name: web200
spec:
  ports:
   - port: 4738
     targetPort: 4738
  selector:
    app: web200
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web200
spec:
  podSelector:
    matchLabels:
      app: web200
  ingress:
  - ports:
    - port: 4738
    from: []
